import { NextRequest, NextResponse } from "next/server";
import { demoClients, demoMetrics } from "@/lib/demo-data";
import { isAuthenticated, unauthorized } from "@/lib/auth";
import { hasDatabase, prisma } from "@/lib/prisma";
import { channelLabels } from "@/lib/reporting";
type ClientViewRecord = { id: string; name: string; phoneNumber: string; status: string; project: string; location: string; acquisitionChannel: string; operationToTake: string; firstContactPerson: string; lastUpdateDate: Date | string };
const clientView = (client: ClientViewRecord) => ({ id: client.id, clientName: client.name, phone: client.phoneNumber, status: client.status, project: client.project, location: client.location, channel: channelLabels[client.acquisitionChannel as keyof typeof channelLabels], nextAction: client.operationToTake, assignee: client.firstContactPerson, updated: client.lastUpdateDate });
export async function GET(request: NextRequest) { if (!isAuthenticated(request)) return unauthorized(); if (!hasDatabase()) return NextResponse.json({ channels: demoMetrics.map(metric => ({ name: channelLabels[metric.channel as keyof typeof channelLabels], short: String(metric.channel).slice(0, 1), accent: "#7266d7", spend: metric.spend, customers: demoClients.filter(c => c.acquisitionChannel === metric.channel && c.status === "WON").length, reach: String(metric.reach), trend: 0 })), leads: demoClients.map(clientView), source: "demo" }); const clients = await prisma.client.findMany({ orderBy: { lastUpdateDate: "desc" } }); const metrics = await prisma.marketingMetric.findMany(); return NextResponse.json({ channels: metrics.map(metric => ({ name: channelLabels[metric.channel], short: metric.channel.slice(0, 1), accent: "#7266d7", spend: Number(metric.spend), customers: clients.filter(c => c.acquisitionChannel === metric.channel && c.status === "WON").length, reach: String(metric.reach), trend: 0 })), leads: clients.map(clientView), source: "postgres" }); }
export async function POST(request: NextRequest) { if (!isAuthenticated(request)) return unauthorized(); const body = await request.json(); return NextResponse.json({ lead: { id: `demo-${Date.now()}`, clientName: body.clientName, phone: body.phone, status: "WAITING", project: body.project, location: "Not set", channel: body.channel, nextAction: "First contact", assignee: "Amira", updated: new Date().toISOString() } }, { status: 201 }); }
