import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { demoClients } from "@/lib/demo-data";
import { isAuthenticated, unauthorized } from "@/lib/auth";
import { hasDatabase, prisma } from "@/lib/prisma";
import { parseChannel, parseStatus } from "@/lib/reporting";
const schema = z.object({ name: z.string().min(2), phoneNumber: z.string().min(5), status: z.string().default("WAITING"), project: z.string().min(1), location: z.string().min(1), acquisitionChannel: z.string().min(1), operationToTake: z.string().min(1), firstContactPerson: z.string().min(1), secondContactPerson: z.string().min(1) });
const filtered = (request: NextRequest) => { const q = request.nextUrl.searchParams; return { channel: parseChannel(q.get("channel")), status: parseStatus(q.get("status")), location: q.get("location")?.toLowerCase(), salesperson: q.get("salesperson")?.toLowerCase() }; };
export async function GET(request: NextRequest) { if (!isAuthenticated(request)) return unauthorized(); const f = filtered(request); if (!hasDatabase()) return NextResponse.json({ source: "demo", clients: demoClients.filter(c => (!f.channel || c.acquisitionChannel === f.channel) && (!f.status || c.status === f.status) && (!f.location || c.location.toLowerCase().includes(f.location)) && (!f.salesperson || c.firstContactPerson.toLowerCase().includes(f.salesperson) || c.secondContactPerson.toLowerCase().includes(f.salesperson))) }); const clients = await prisma.client.findMany({ where: { acquisitionChannel: f.channel, status: f.status, location: f.location ? { contains: f.location, mode: "insensitive" } : undefined, OR: f.salesperson ? [{ firstContactPerson: { contains: f.salesperson, mode: "insensitive" } }, { secondContactPerson: { contains: f.salesperson, mode: "insensitive" } }] : undefined }, orderBy: { lastUpdateDate: "desc" } }); return NextResponse.json({ source: "postgres", clients }); }
export async function POST(request: NextRequest) { if (!isAuthenticated(request)) return unauthorized(); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 }); const value = parsed.data; const acquisitionChannel = parseChannel(value.acquisitionChannel); const status = parseStatus(value.status) || "WAITING"; if (!acquisitionChannel) return NextResponse.json({ error: "Invalid acquisition channel" }, { status: 400 }); if (!hasDatabase()) return NextResponse.json({ source: "demo", client: { id: `demo-${Date.now()}`, ...value, status, acquisitionChannel, createdAt: new Date().toISOString(), lastUpdateDate: new Date().toISOString() } }, { status: 201 }); const client = await prisma.client.create({ data: { ...value, status, acquisitionChannel } }); return NextResponse.json({ source: "postgres", client }, { status: 201 }); }
export async function PATCH(request: NextRequest) { if (!isAuthenticated(request)) return unauthorized(); const body = await request.json(); const id = String(body.id || ""); const data = { ...(body.status ? { status: parseStatus(body.status) } : {}), ...(body.acquisitionChannel ? { acquisitionChannel: parseChannel(body.acquisitionChannel) } : {}), ...(typeof body.operationToTake === "string" ? { operationToTake: body.operationToTake } : {}), ...(typeof body.firstContactPerson === "string" ? { firstContactPerson: body.firstContactPerson } : {}), ...(typeof body.secondContactPerson === "string" ? { secondContactPerson: body.secondContactPerson } : {}) }; if (!id || Object.values(data).some(value => value === undefined)) return NextResponse.json({ error: "Invalid update" }, { status: 400 }); if (!hasDatabase()) return NextResponse.json({ source: "demo", client: { id, ...data, lastUpdateDate: new Date().toISOString() } }); const client = await prisma.client.update({ where: { id }, data }); return NextResponse.json({ source: "postgres", client }); }
