// English source of truth for every i18n key. Author here; the generator
// (work/gen_i18n.js) merges this with the recovered Arabic block.
module.exports = {
  // ── Common ──
  "common.save": "Save",
  "common.saveChanges": "Save changes",
  "common.cancel": "Cancel",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.close": "Close",
  "common.loading": "Loading…",
  "common.export": "Export",
  "common.search": "Search",
  "common.back": "Back",

  // ── Nav / header ──
  "nav.dashboard": "Dashboard",
  "nav.clients": "Clients",
  "nav.archived": "Archived",
  "nav.marketing": "Marketing",
  "nav.settings": "Settings",
  "header.notifications": "Notifications",
  "header.markAllRead": "Mark all as read",
  "header.allCaughtUp": "All caught up",
  "header.viewAll": "Show all",
  "header.signOut": "Sign out",
  "header.switchLight": "Light mode",
  "header.switchDark": "Dark mode",
  "header.menu": "Menu",

  // ── Dashboard ──
  "dash.exportReport": "Export report",
  "dash.exporting": "Exporting…",
  "dash.clientsInView": "clients in view",
  "dash.heroTitle": "Your pipeline. A clearer picture.",
  "dash.heroSubtitle": "Clients, channels and team performance — all in one place.",
  "dash.workspaceOverview": "Workspace Overview",
  "dash.clientOverview": "Client overview",
  "dash.clientsInThisView": "clients in this view",
  "kpi.totalSpend": "Total spend",
  "kpi.weeklyInvestment": "Weekly investment",
  "kpi.totalReach": "Total reach",
  "kpi.acrossChannels": "across channels",
  "kpi.won": "Won",
  "kpi.winRate": "win rate",
  "kpi.lost": "Lost",
  "kpi.ofTotal": "of total",
  "kpi.pipeline": "Pipeline",
  "kpi.awaiting": "Awaiting",
  "kpi.avgCpa": "Avg CPA",
  "kpi.customersWon": "{n} customers won",
  "kpi.noWins": "No wins yet",
  "funnel.title": "Conversion funnel",
  "funnel.total": "Total clients",
  "funnel.waiting": "Waiting",
  "funnel.won": "Won",
  "funnel.lost": "Lost",
  "sp.title": "Sales performance",
  "sp.noData": "No sales data yet",
  "roi.title": "Channel ROI",
  "roi.channel": "Channel",
  "roi.spend": "Spend",
  "roi.won": "Won",
  "roi.cpa": "CPA",
  "recent.title": "Recent clients",
  "recent.empty": "No clients were created recently",
  "recent.project": "Project",
  "recent.location": "Location",
  "loc.title": "Top locations",
  "loc.clients": "{n} clients",
  "loc.noData": "No location data yet",
  "brk.title": "Channel breakdown",
  "brk.platform": "Platform",
  "brk.reach": "Reach",
  "brk.clients": "clients",

  // ── Clients page / table ──
  "clients.title": "Clients",
  "clients.subtitle": "Manage your sales pipeline. Click any client to view details.",
  "clients.table": "Table",
  "clients.kanban": "Kanban",
  "clients.newClient": "New client",
  "clients.exportSelected": "Export selected",
  "clients.exportAll": "Export all",
  "clients.showing": "showing",
  "clients.selected": "selected",
  "clients.deleteSelected": "Delete selected",
  "clients.archiveSelected": "Archive selected",
  "filter.allStatuses": "All statuses",
  "filter.allChannels": "All channels",
  "filter.allLocations": "All locations",
  "filter.allSalespeople": "All salespeople",
  "filter.queryPh": "Filter by phone, name, or project…",
  "filter.clear": "Clear filters",
  "filter.addStatus": "Add status",
  "filter.addChannel": "Add channel",
  "filter.addLocation": "Add location",
  "date.today": "Today",
  "date.week": "This week",
  "date.last7": "Last 7 days",
  "date.month": "This month",
  "th.client": "Client",
  "th.status": "Status",
  "th.source": "Source",
  "th.project": "Project",
  "th.location": "Location",
  "th.date": "Date",

  // ── Statuses ──
  "status.waiting": "Waiting",
  "status.won": "Won",
  "status.lost": "Lost",
  "status.new": "New",

  // ── Client detail ──
  "client.field.name": "Name",
  "client.field.phone": "Phone",
  "client.field.status": "Status",
  "client.field.source": "Source",
  "client.field.channel": "Channel",
  "client.field.project": "Project",
  "client.field.location": "Location",
  "client.field.operation": "Operation to take",
  "client.field.firstContact": "First contact person",
  "client.field.secondContact": "Second contact person",
  "client.field.notes": "Notes",
  "client.field.created": "Created",
  "client.noActivity": "No activity yet",

  // ── Toast ──
  "toast.created": "Client {name} created",

  // ── Settings ──
  "settings.title": "Settings",
  "settings.preferences": "Preferences",
  "settings.language": "Language",
  "settings.account": "Account",
  "settings.profile": "Profile",
  "settings.changePassword": "Change password",
  "settings.teamMembers": "Team Members",
  "settings.addUser": "Add user",
  "settings.dangerZone": "Danger zone",
  "settings.clearLocal": "Clear local data",
  "settings.signOut": "Sign out",
  "settings.profileSaved": "Profile saved successfully",
  "settings.passwordChanged": "Password changed successfully",
    "settings.darkMode": "Dark mode",
  "settings.lightMode": "Light mode",
  "settings.subtitle": "Manage your account and preferences.",
  "settings.profileSubtitle": "Your public information",
  "settings.saveProfile": "Save profile",
  "settings.field.fullName": "Full name",
  "settings.field.email": "Email",
  "settings.field.username": "Username",
  "settings.field.role": "Role",
  "settings.noEmail": "No email set",
  "settings.remove": "Remove",
  "settings.saving": "Saving…",
  "settings.passwordSubtitle": "Update your login credentials",
  "settings.field.currentPassword": "Current password",
  "settings.field.newPassword": "New password",
  "settings.updatePassword": "Update password",
  "settings.noTeam": "No team members yet.",
  "settings.dangerZoneSubtitle": "Irreversible actions",
};
