module.exports = {
  "detail.back": ["Back", "رجوع"],
  "detail.notFound": ["Client not found.", "العميل غير موجود."],
  "detail.loadFail": ["Couldn’t load client.", "تعذّر تحميل العميل."],
  "detail.day": ["day", "يوم"],
  "detail.days": ["days", "يوم"],
  "detail.createdAgo": ["Created {n} days ago", "أُنشئ منذ {n} يوم"],
  "detail.createdToday": ["Created today", "أُنشئ اليوم"],
  "detail.saveChanges": ["Save changes", "حفظ التغييرات"],
  "detail.saved": ["Client updated", "تم تحديث العميل"],
  "detail.saveFail": ["Couldn’t save changes.", "تعذّر حفظ التغييرات."],
  "detail.deleteTitle": ["Delete client?", "حذف العميل؟"],
  "detail.deleteBody": ["This will permanently delete “{name}”. This cannot be undone.", "سيؤدي هذا إلى حذف “{name}” نهائياً. لا يمكن التراجع."],
  "detail.deleted": ["Client deleted", "تم حذف العميل"],
  "detail.deleteFail": ["Couldn’t delete client.", "تعذّر حذف العميل."],
  "detail.timeline": ["Activity timeline", "الجدول الزمني للأنشطة"],
  "detail.details": ["Client details", "تفاصيل العميل"],
  "detail.info": ["Contact info", "معلومات التواصل"],
  "detail.stats": ["Stats", "إحصائيات"],
  "detail.edit": ["Edit", "تعديل"],
  "detail.delete": ["Delete", "حذف"],
  "detail.operation": ["Operation to take", "العملية المطلوبة"],
  "detail.assigned": ["Assigned to", "المسؤول"],
  "detail.unassigned": ["Unassigned", "غير مُسند"],
  "detail.sinceCreation": ["Since creation", "منذ الإنشاء"],
  "detail.lastUpdate": ["Last update", "آخر تحديث"],
  "detail.activities": ["Activities", "الأنشطة"],
  "archive.crumbs": ["Archive", "الأرشيف"],
  "archive.title": ["Archived clients", "العملاء المؤرشفون"],
  "archive.sub": ["Archived clients stay here safely. Restore them any time, or delete permanently if you're an admin.", "يبقى العملاء المؤرشفون هنا بأمان. استعدهم في أي وقت، أو احذفهم نهائياً إذا كنت مديراً."],
  "archive.searchPh": ["Search archived clients…", "ابحث في العملاء المؤرشفين..."],
  "archive.adminNote": ["Only admins can archive, restore, or permanently delete clients. Your access here is read-only.", "فقط المديرون يمكنهم الأرشفة أو الاستعادة أو الحذف النهائي. وصولك هنا للقراءة فقط."],
  "archive.heading": ["Archive", "الأرشيف"],
  "archive.clientsCount": ["{n} client(s)", "{n} عميل"],
  "archive.adminFull": ["Admin — full control", "مدير — تحكم كامل"],
  "archive.readOnly": ["{role} — read only", "{role} — قراءة فقط"],
  "archive.loading": ["Loading archived clients…", "جارٍ تحميل العملاء المؤرشفين..."],
  "archive.nothing": ["Nothing archived yet", "لا يوجد أرشيف بعد"],
  "archive.nothingSub": ["Clients you archive will appear here.", "العملاء الذين تؤرشفهم سيظهرون هنا."],
  "archive.noMatch": ["No matches", "لا توجد نتائج"],
  "archive.noMatchSub": ["Try a different search.", "جرّب بحثاً مختلفاً."],
  "archive.restored": ["“{name}” restored", "تمت استعادة “{name}”"],
  "archive.restoreFail": ["Could not restore client", "تعذّرت استعادة العميل"],
  "archive.deleteConfirm": ["Permanently delete “{name}”? This cannot be undone.", "حذف “{name}” نهائياً؟ لا يمكن التراجع عن هذا."],
  "archive.deleted": ["“{name}” deleted", "تم حذف “{name}”"],
  "archive.deleteFail": ["Could not delete client", "تعذّر حذف العميل"],
  "archive.deleteTitle": ["Delete permanently", "حذف نهائي"],
  "archive.archivedLabel": ["Archived", "مؤرشف"],
  "notif.crumbs": ["Notifications", "الإشعارات"],
  "notif.title": ["Notifications", "الإشعارات"],
  "notif.sub": ["New alerts stay here until you read them. Read ones move to history.", "تبقى التنبيهات الجديدة هنا حتى تقرأها. المقروءة تنتقل إلى السجل."],
  "notif.markAll": ["Mark all read", "تحديد الكل كمقروء"],
  "notif.clearHistory": ["Clear history ({n})", "مسح السجل ({n})"],
  "notif.clearConfirm": ["Clear {n} notification(s) from history?", "مسح {n} إشعار من السجل؟"],
  "notif.new": ["New", "الجديدة"],
  "notif.newCount": ["{n} new", "{n} جديدة"],
  "notif.history": ["History", "السجل"],
  "notif.loading": ["Loading notifications…", "جارٍ تحميل الإشعارات..."],
  "notif.historyEmpty": ["History is empty", "السجل فارغ"],
  "notif.historySub": ["Read notifications are saved here until you delete them.", "تُحفظ الإشعارات المقروءة هنا حتى تحذفها."],
  "notif.caughtUp": ["You're all caught up", "لا جديد لديك"],
  "notif.caughtUpSub": ["No new notifications right now.", "لا توجد إشعارات جديدة الآن."],
  "notif.markRead": ["Mark read", "تحديد كمقروء"],
  "notif.deleteTitle": ["Delete", "حذف"],
  "notif.updateFail": ["Unable to update notifications. Please try again.", "تعذّر تحديث الإشعارات. حاول مرة أخرى."],
  "notif.updateFailShort": ["Unable to update notifications.", "تعذّر تحديث الإشعارات."],
};
