module.exports = {
  "form.name": ["Name", "الاسم"],
  "form.phone": ["Phone", "الهاتف"],
  "form.status": ["Status", "الحالة"],
  "form.channel": ["Channel", "القناة"],
  "form.project": ["Project", "المشروع"],
  "form.projectPh": ["e.g. North Coast villa", "مثال: فيلا في الساحل الشمالي"],
  "form.projectDetailsPh": ["Project details…", "تفاصيل المشروع..."],
  "form.location": ["Location", "الموقع"],
  "form.locationPh": ["Select location…", "اختر الموقع..."],
  "form.operation": ["Operation to take", "العملية المطلوبة"],
  "form.operationPh": ["e.g. Follow-up call tomorrow", "مثال: مكالمة متابعة غداً"],
  "form.firstContact": ["First contact person", "جهة التواصل الأولى"],
  "form.secondContact": ["Second contact person", "جهة التواصل الثانية"],
  "form.assignedTo": ["Assigned to", "المسؤول"],
  "form.unassigned": ["Unassigned", "غير مُسند"],
  "form.notes": ["Notes", "ملاحظات"],
  "form.notesPh": ["Anything worth remembering…", "أي شيء يستحق التذكر..."],
  "form.channelPh": ["Select channel…", "اختر القناة..."],
  "form.statusPh": ["Select status…", "اختر الحالة..."],
  "form.newValuePh": ["New value…", "قيمة جديدة..."],
  "form.addNewOpt": ["＋ Add new…", "＋ إضافة جديد..."],
  "form.addBtn": ["Add", "إضافة"],
  "form.required": ["Required", "مطلوب"],
  "form.afterStart": ["Must be after start", "يجب أن يكون بعد البداية"],
  "mkt.workspace": ["MARKETING WORKSPACE", "مساحة عمل التسويق"],
  "mkt.title": ["Make every campaign count.", "اجعل كل حملة ذات قيمة."],
  "mkt.sub": ["Your investment, audience, and channel performance in one place.", "استثمارك وجمهورك وأداء قنواتك في مكان واحد."],
  "mkt.exportExcel": ["Export Excel", "تصدير إكسل"],
  "mkt.exportFail": ["Export failed. Please try again.", "فشل التصدير. حاول مرة أخرى."],
  "mkt.addMetric": ["Add metric", "إضافة مؤشر"],
  "mkt.editMetric": ["Edit metric", "تعديل المؤشر"],
  "mkt.totalSpend": ["Total spend", "إجمالي الإنفاق"],
  "mkt.totalReach": ["Total reach", "إجمالي الوصول"],
  "mkt.avgCpm": ["Avg CPM", "متوسط التكلفة لكل ألف"],
  "mkt.avgCpc": ["Avg CPC", "متوسط التكلفة لكل نقرة"],
  "mkt.newChannel": ["New channel name", "اسم القناة الجديدة"],
  "mkt.newChannelPh": ["e.g. LINKEDIN", "مثال: LINKEDIN"],
  "mkt.startDate": ["Start date", "تاريخ البداية"],
  "mkt.endDate": ["End date", "تاريخ النهاية"],
  "mkt.spend": ["Spend ($)", "الإنفاق ($)"],
  "mkt.reach": ["Reach", "الوصول"],
  "mkt.clicks": ["Clicks", "النقرات"],
  "mkt.impressions": ["Impressions", "مرات الظهور"],
  "mkt.notes": ["Notes", "ملاحظات"],
  "mkt.notesPh": ["Optional notes…", "ملاحظات اختيارية..."],
  "mkt.addCustom": ["+ Add custom channel…", "+ إضافة قناة مخصصة..."],
  "mkt.deleteConfirm": ["Delete this metric?", "حذف هذا المؤشر؟"],
};
