// Round 6 — final gaps (dashboard toasts, settings admin surfaces, API errors).
module.exports = {
  "common.remove": ["Remove", "إزالة"],
  "common.saving": ["Saving…", "جارٍ الحفظ..."],
  "form.noneOption": ["-- None --", "— بدون —"],
  "form.errNameMin": ["Name must be at least 2 characters", "الاسم يجب أن يكون حرفين على الأقل"],
  "form.errPhoneMin": ["Phone number must be at least 5 characters", "رقم الجوال يجب أن يكون 5 أرقام على الأقل"],
  "form.selectPh": ["Select {label}...", "اختر {label}..."],
  "form.saveValue": ["+ Save “{value}”", "+ حفظ “{value}”"],
  "th.first": ["1st", "المسؤول الأول"],
  "th.second": ["2nd", "المسؤول الثاني"],
  "clients.noSelection": ["No clients selected", "لا يوجد عملاء محددون"],
  "settings.profileSaved": ["Profile saved successfully", "تم حفظ الملف الشخصي"],
  "settings.passwordChanged": ["Password changed successfully", "تم تغيير كلمة المرور"],
  "settings.userUpdated": ["User updated", "تم تحديث المستخدم"],
  "settings.errSaveFail": ["Couldn’t save changes", "تعذّر حفظ التغييرات"],
  "settings.errUpdateFail": ["Couldn’t update user", "تعذّر تحديث المستخدم"],
  "settings.errGeneric": ["Couldn’t complete the operation", "تعذّر إتمام العملية"],
  "settings.errPasswordMin": ["Password must be at least 6 characters", "كلمة المرور يجب أن تكون 6 أحرف على الأقل"],
  "settings.errPasswordMinShort": ["Password min 6 chars", "كلمة المرور: 6 أحرف على الأقل"],
  "settings.errUserRequired": ["Name, username, and password are required", "الاسم واسم المستخدم وكلمة المرور مطلوبة"],
  "settings.errAvatarTooBig": ["Image is too large (max 2MB)", "حجم الصورة كبير جداً (الحد الأقصى 2 ميجابايت)"],
  "settings.avatarHint": ["Upload a photo (max 2MB). Shown on your profile.", "ارفع صورة (بحد أقصى 2 ميجابايت) لتظهر في ملفك الشخصي."],
  "settings.avatarAlt": ["Avatar", "الصورة الشخصية"],
  "settings.changePhoto": ["Change photo", "تغيير الصورة"],
  "settings.clearLocalBody": ["Clear all locally stored data including clients, metrics, and custom statuses. This cannot be undone.", "مسح كل البيانات المحفوظة محلياً، بما في ذلك العملاء والمؤشرات والحالات المخصصة. لا يمكن التراجع عن هذا الإجراء."],
  "settings.clearLocalConfirm": ["Clear all local data?", "مسح جميع البيانات المحلية؟"],
  "settings.deleteUserConfirm": ["Delete user “{name}”?", "حذف المستخدم “{name}”؟"],
  "settings.editUser": ["Edit user", "تعديل المستخدم"],
  "settings.deleteUserTitle": ["Delete user", "حذف المستخدم"],
  "settings.currentPasswordPh": ["Enter current password", "أدخل كلمة المرور الحالية"],
  "settings.passwordMinPh": ["At least 6 characters", "6 أحرف على الأقل"],
  "settings.fullNamePh": ["Full name", "الاسم الكامل"],
  "settings.usernamePh": ["username", "اسم المستخدم"],
  "settings.emailPh": ["email@example.com", "email@example.com"],
  "settings.field.password": ["Password", "كلمة المرور"],
  "auth.togglePassword": ["Toggle password visibility", "إظهار أو إخفاء كلمة المرور"],
  "errors.generic": ["Something went wrong. Please try again.", "تعذّر إتمام العملية. حاول مرة أخرى."],
  "errors.adminOnly": ["Only admins can do this.", "هذه العملية متاحة للمديرين فقط."],
  "errors.usernamePasswordRequired": ["Username and password are required.", "اسم المستخدم وكلمة المرور مطلوبان."],
  "errors.badCredentials": ["Incorrect username or password.", "اسم المستخدم أو كلمة المرور غير صحيحة."],
  "errors.usernameMin": ["Username must be at least 2 characters.", "اسم المستخدم يجب أن يكون حرفين على الأقل."],
  "errors.usernameTaken": ["Username is already taken.", "اسم المستخدم مستخدم بالفعل."],
  "errors.nameRequired": ["Name is required.", "الاسم مطلوب."],
  "errors.nameEmpty": ["Name cannot be empty.", "الاسم لا يمكن أن يكون فارغاً."],
  "errors.passwordMin": ["Password must be at least 6 characters.", "كلمة المرور يجب أن تكون 6 أحرف على الأقل."],
  "errors.userNotFound": ["User not found.", "المستخدم غير موجود."],
  "errors.cannotDeleteSelf": ["You cannot delete your own account.", "لا يمكنك حذف حسابك."],
  "errors.cannotChangeOwnRole": ["You cannot change your own role away from Admin.", "لا يمكنك إلغاء دور المدير عن حسابك."],
  "errors.missingId": ["Missing identifier.", "المعرّف مفقود."],
  "errors.clientNotFound": ["Client not found.", "العميل غير موجود."],
  "errors.channelInvalid": ["Invalid channel.", "قناة غير صحيحة."],
  "errors.adminArchiveOnly": ["Only admins can archive or restore clients.", "أرشفة العملاء أو استعادتهم متاحة للمديرين فقط."],
  "errors.adminDeleteOnly": ["Only admins can permanently delete clients. Archive it instead.", "الحذف النهائي للعملاء متاح للمديرين فقط. استخدم الأرشفة بدلاً من ذلك."],
  "errors.statusRequired": ["Status label is required.", "اسم الحالة مطلوب."],
  "errors.statusInvalid": ["Invalid status label.", "اسم الحالة غير صحيح."],
  "errors.statusExists": ["Status already exists.", "الحالة موجودة بالفعل."],
  "errors.channelRequired": ["Channel name is required.", "اسم القناة مطلوب."],
  "errors.channelExists": ["Channel already exists.", "القناة موجودة بالفعل."],
  "errors.locationRequired": ["Location name is required.", "اسم الموقع مطلوب."],
  "errors.locationExists": ["Location already exists.", "الموقع موجود بالفعل."],
  "errors.notificationIdRequired": ["Notification id is required.", "معرّف الإشعار مطلوب."],
  "errors.metricFieldsRequired": ["Channel, start date, and end date are required.", "القناة وتاريخ البداية وتاريخ النهاية مطلوبة."],
  "errors.dateOrder": ["End date must be on or after the start date.", "تاريخ النهاية يجب أن يكون بعد تاريخ البداية أو مساوياً له."],
  "errors.nonNegative": ["Numbers must be non-negative.", "الأرقام يجب أن تكون غير سالبة."],
  "errors.metricExists": ["A metric already exists for this channel and date range.", "يوجد مؤشر مسجّل لنفس القناة والفترة."],
  "errors.notFound": ["Not found.", "العنصر غير موجود."],
};
