module.exports = {
  "status.waitingLabel": ["Waiting", "بالانتظار"],
  "status.wonLabel": ["Won", "مكسب"],
  "status.lostLabel": ["Lost", "خسارة"],
  "ch.facebook": ["Facebook", "فيسبوك"],
  "ch.instagram": ["Instagram", "انستغرام"],
  "ch.tiktok": ["TikTok", "تيك توك"],
  "ch.googleAds": ["Google Ads", "إعلانات جوجل"],
  "ch.whatsapp": ["WhatsApp", "واتساب"],
  "ch.calls": ["Calls", "مكالمات"],
  "ch.sales": ["Sales", "المبيعات"],
  "ch.all": ["All channels", "كل القنوات"],
  "dash.heroEyebrow": ["RWAQ / WORKSPACE OVERVIEW", "رواق / نظرة على مساحة العمل"],
  "dash.allTime": ["All-time overview", "نظرة شاملة"],
  "dash.trackedSpend": ["Tracked spend", "الإنفاق المتتبع"],
  "dash.activeChannels": ["Active channels", "القنوات النشطة"],
  "dash.totalClicks": ["Total clicks", "إجمالي النقرات"],
  "dash.recordsLogged": ["Records logged", "السجلات المسجلة"],
  "dash.kpiRecords": ["{n} records", "{n} سجل"],
  "dash.kpiReachSub": ["Impressions reached", "مرات الظهور المحققة"],
  "dash.kpiCpmSub": ["Cost per 1K reach", "التكلفة لكل ألف وصول"],
  "dash.kpiCpcSub": ["Cost per click", "التكلفة لكل نقرة"],
  "dash.loadingMetrics": ["Loading metrics…", "جارٍ تحميل المؤشرات..."],
  "dash.clearFilters": ["Clear filters", "مسح الفلاتر"],
  "dash.bestChannel": ["Most efficient channel", "القناة الأكثر كفاءة"],
  "dash.worstChannel": ["Highest cost channel", "القناة الأعلى تكلفة"],
  "dash.peakPeriod": ["Peak period", "فترة الذروة"],
  "dash.notEnough": ["Not enough data", "لا توجد بيانات كافية"],
  "dash.trendEyebrow": ["INVESTMENT TREND", "اتجاه الاستثمار"],
  "dash.trendTitle": ["Spend over time", "الإنفاق عبر الزمن"],
  "dash.trendNote": ["Latest 6 months with records", "آخر 6 أشهر مسجلة"],
  "dash.budgetEyebrow": ["BUDGET DISTRIBUTION", "توزيع الميزانية"],
  "dash.budgetTitle": ["Spend by channel", "الإنفاق حسب القناة"],
  "dash.channelsCount": ["{n} channels", "{n} قناة"],
  "dash.breakdownEmpty": ["No channel data yet. Click “Add metric” to record your first entry.", "لا توجد بيانات قنوات بعد. اضغط “إضافة مؤشر” لتسجيل أول إدخال."],
  "dash.recentEntries": ["Recent entries", "أحدث الإدخالات"],
  "dash.totalSuffix": ["total", "الإجمالي"],
  "dash.noMetrics": ["No metrics recorded yet.", "لا توجد مؤشرات مسجلة بعد."],
  "dash.thChannel": ["Channel", "القناة"],
  "dash.thPeriod": ["Period", "الفترة"],
  "dash.thSpend": ["Spend", "الإنفاق"],
  "dash.thReach": ["Reach", "الوصول"],
  "dash.thClicks": ["Clicks", "النقرات"],
  "dash.thCpm": ["CPM", "التكلفة لكل ألف"],
  "dash.thCpc": ["CPC", "التكلفة لكل نقرة"],
  "dash.thNotes": ["Notes", "ملاحظات"],
  "dash.cpmSpend": ["{cpm} CPM · {spend} spend", "{cpm} لكل ألف · إنفاق {spend}"],
  "dash.spendOnly": ["{spend} spend", "إنفاق {spend}"],
  "dash.reachCount": ["{n} reach", "{n} وصول"],
};
