module.exports = {
  "common.add": ["Add", "إضافة"],
  "common.retry": ["Retry", "إعادة المحاولة"],
  "common.apply": ["Apply", "تطبيق"],
  "common.clear": ["Clear", "مسح"],
  "common.confirm": ["Confirm", "تأكيد"],
  "common.all": ["All", "الكل"],
  "common.from": ["From", "من"],
  "common.to": ["To", "إلى"],
  "common.total": ["Total", "الإجمالي"],
  "common.records": ["{n} records", "{n} سجل"],
  "common.noData": ["No data yet", "لا توجد بيانات بعد"],
  "common.loadMore": ["Load more", "عرض المزيد"],
  "common.today": ["Today", "اليوم"],
  "common.justNow": ["Just now", "الآن"],
  "common.minAgo": ["{n}m ago", "منذ {n} دقيقة"],
  "common.hourAgo": ["{n}h ago", "منذ {n} ساعة"],
  "common.dayAgo": ["{n}d ago", "منذ {n} يوم"],
  "common.archivedOn": ["Archived {date}", "أُرشف في {date}"],
  "auth.workspace": ["growth workspace", "مساحة عمل النمو"],
  "auth.privateWorkspace": ["Private workspace", "مساحة عمل خاصة"],
  "auth.welcomeBack": ["Welcome back.", "مرحباً بعودتك."],
  "auth.signinSub": ["Sign in to see your growth engine in motion.", "سجّل الدخول لترى محرك نموّك يعمل."],
  "auth.username": ["Username", "اسم المستخدم"],
  "auth.usernamePh": ["Enter your username", "أدخل اسم المستخدم"],
  "auth.password": ["Password", "كلمة المرور"],
  "auth.passwordPh": ["Enter your password", "أدخل كلمة المرور"],
  "auth.signingIn": ["Signing in…", "جارٍ تسجيل الدخول..."],
  "auth.signIn": ["Sign in", "تسجيل الدخول"],
  "auth.badCredentials": ["Incorrect username or password.", "اسم المستخدم أو كلمة المرور غير صحيحة."],
  "auth.brand": ["Rwaq Marketing", "رواق للتسويق"],
  "auth.createAccount": ["Create account", "إنشاء حساب"],
  "auth.createWorkspace": ["Create your workspace", "أنشئ مساحة عملك"],
  "auth.joinTitle": ["Join Rwaq.", "انضم إلى رواق."],
  "auth.joinSub": ["Set up your account and start tracking growth.", "أنشئ حسابك وابدأ تتبع النمو."],
  "auth.fullName": ["Full name", "الاسم الكامل"],
  "auth.fullNamePh": ["e.g. Amira Mansour", "مثال: أميرة منصور"],
  "auth.usernamePickPh": ["Choose a username", "اختر اسم مستخدم"],
  "auth.min6": ["At least 6 characters", "6 أحرف على الأقل"],
  "auth.creating": ["Creating account…", "جارٍ إنشاء الحساب..."],
  "auth.haveAccount": ["Already have an account?", "لديك حساب بالفعل؟"],
  "auth.asideKicker": ["RWQ / 2026", "رواق / 2026"],
  "auth.asideWeekly": ["Weekly intelligence", "ذكاء أسبوعي"],
  "auth.asideTitleA": ["Start your", "ابدأ"],
  "auth.asideTitleB": ["growth engine", "محرك نموّك"],
  "auth.asideSub": ["Create an account and take full control of your marketing pipeline.", "أنشئ حساباً وتحكّم بالكامل في مسارك التسويقي."],
};
