module.exports = {
  "clients.crm": ["CRM", "إدارة العملاء"],
  "clients.selectedCount": ["{n} selected", "{n} محدد"],
  "clients.selectAll": ["Select all", "تحديد الكل"],
  "clients.clearSelection": ["Clear", "مسح التحديد"],
  "clients.restore": ["Restore", "استعادة"],
  "clients.deleteTitle": ["Delete {n} client(s)?", "حذف {n} عميل؟"],
  "clients.deleteBody": ["This will permanently delete the selected clients. This cannot be undone.", "سيؤدي هذا إلى حذف العملاء المحددين نهائياً. لا يمكن التراجع عن هذا الإجراء."],
  "clients.archiveTitle": ["Archive {n} client(s)?", "أرشفة {n} عميل؟"],
  "clients.archiveBody": ["Archived clients move to the Archive tab and can be restored later.", "ينتقل العملاء المؤرشفون إلى تبويب الأرشيف ويمكن استعادتهم لاحقاً."],
  "clients.exportSelectedBtn": ["Export selected", "تصدير المحدد"],
  "clients.exportingBtn": ["Exporting…", "جارٍ التصدير..."],
  "clients.exportAllBtn": ["Export all", "تصدير الكل"],
  "clients.exportFilteredBtn": ["Export filtered", "تصدير المصفّى"],
  "clients.exportEmpty": ["Nothing to export.", "لا يوجد ما يُصدَّر."],
  "clients.exportFail": ["Export failed.", "فشل التصدير."],
  "clients.deleteOneTitle": ["Delete client?", "حذف العميل؟"],
  "clients.deleteOneBody": ["This will permanently delete “{name}”. This cannot be undone.", "سيؤدي هذا إلى حذف “{name}” نهائياً. لا يمكن التراجع عن هذا الإجراء."],
  "clients.archiveOneTitle": ["Archive client?", "أرشفة العميل؟"],
  "clients.archiveOneBody": ["“{name}” will move to the Archive tab and can be restored later.", "سينتقل “{name}” إلى تبويب الأرشيف ويمكن استعادته لاحقاً."],
  "clients.loadFail": ["Couldn’t load clients.", "تعذّر تحميل العملاء."],
  "clients.noResults": ["No clients match your filters.", "لا يوجد عملاء يطابقون الفلاتر."],
  "clients.noClients": ["No clients yet. Click “New client” to add your first one.", "لا يوجد عملاء بعد. اضغط “عميل جديد” لإضافة أول عميل."],
  "clients.waitingCol": ["Waiting", "بالانتظار"],
  "clients.wonCol": ["Won", "مكسب"],
  "clients.lostCol": ["Lost", "خسارة"],
  "clients.addTitle": ["New client", "عميل جديد"],
  "clients.editTitle": ["Edit client", "تعديل العميل"],
  "clients.createBtn": ["Create client", "إنشاء العميل"],
  "clients.saveBtn": ["Save changes", "حفظ التغييرات"],
  "clients.createdToast": ["Client “{name}” created", "تم إنشاء العميل “{name}”"],
  "clients.updatedToast": ["Client updated", "تم تحديث العميل"],
  "clients.deletedToast": ["Client deleted", "تم حذف العميل"],
  "clients.archivedToast": ["Client archived", "تمت أرشفة العميل"],
  "clients.bulkDeleted": ["{n} client(s) deleted", "تم حذف {n} عميل"],
  "clients.bulkArchived": ["{n} client(s) archived", "تمت أرشفة {n} عميل"],
  "clients.opFail": ["Operation failed.", "فشلت العملية."],
  "clients.addFirst": ["Add your first client to get started.", "أضف أول عميل للبدء."],
  "clients.addClientBtn": ["Add client", "إضافة عميل"],
  "clients.searchPh": ["Search clients…", "ابحث عن العملاء..."],
  "clients.noFirstContact": ["No contact", "لا توجد جهة تواصل"],
};
